### ISSUE TITLE
Design/Create database schema

### ISSUE THREAD

**Issue by brenkeys** [brenkeys/weekly-menu-generator#1]
Design the base structure to save recipes in the database.
The following information is needed:
-Recipe title
-Ingredients (including measures and units)
-Directions
-Style (Mexican, French, Indian, Spanish, Italian, etc)
-Classification (Vegetarian, Pork, Beef, Chicken, etc)
-Calories
-Servings

**Comment by noetapia1** [comment]
updated files: 
create_db_structure.sql
and insert_initial_values.sql

to execute the scripts type from your terminal:
mysql -u yourRootUser -p < create_db_structure.sql
mysql -u yourRootUser -p < insert_initial_values.sql
